// <auto-generated />
namespace OopRestaurant201909.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PerhapsthismovestheDBtoSQLExpress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PerhapsthismovestheDBtoSQLExpress));
        
        string IMigrationMetadata.Id
        {
            get { return "201909191255453_Perhaps this moves the DB to SQLExpress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
