// <auto-generated />
namespace OopRestaurant201909.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addLocationdatabasetableandTableLocationproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addLocationdatabasetableandTableLocationproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201910101603552_add Location database table and Table.Location property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
